### Register
POST http://localhost:3005/api/v1/auth/register
Content-Type: application/json

{
    "email": "hoangloc1307@gmail.com",
    "password": "123456"
}



### Login
POST http://localhost:3005/api/v1/auth/login
Content-Type: application/json

{
    "email": "hoangloc13071@gmail.com",
    "password": "123456"
}



### Logout
DELETE http://localhost:3005/api/v1/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZDZhMTQ3LTExYjgtNDQ3Ny1hNDJhLTkyNDE0MzA1YWQxMCIsImVtYWlsIjoiaG9hbmdsb2MxMzA3MUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTY4MDg3NTE5MSwiZXhwIjoxNjgwODc1NDkxfQ.SDg5NoW4epA7fBtjHd8pzuKLud663QFz-oQ-IB764_Y



### Refresh token
POST http://localhost:3005/api/v1/auth/refresh-token
Content-Type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2ZGRjNWUzLTQ4ZTItNDU5NC1iYzQxLTNmOWI5YjZkMzEyMCIsImVtYWlsIjoiaG9hbmdsb2MxMzA3QGdtYWlsLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNjgwODc1MTY2LCJleHAiOjE2ODM0NjcxNjZ9.UGU38prnwdI2kQ2Bp1Sew-ftyFIrVh1_qjdn0_diHsU"
}